[project]
name = "whoispy"
version = "0.1.0"
description = "Who is spy? This game will show"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.4",
    "fastapi==0.135.3",
    "fastapi-cli>=0.0.24",
    "pytest>=9.0.2",
    "sqlalchemy==2.0.48",
]

[tool.fastapi]
entrypoint="app.main:app"
